### ISSUE TITLE
"CodeGenerator" is a confusing name

### ISSUE THREAD

**Issue by GlennCavarle** [blast-project/CoreBundle#32]
"CodeGenerator" is a confusing name for things which do not actually generate source code but which populate a 'code' field of an entity.

So, what is this 'code' field? Is it something like a unique ID or UUID?
What could be the new name?

**Comment by RomainSanchez** [comment]
I guess we could call it UniqueCodeGenerator.It should also move to
BlastUtilsBundle as well IMO

Le 26 juin 2017 10:00 AM, "GlennCavarle" <notifications@github.com> a
écrit :
